// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RapPhimOOSD.Models;

namespace RapPhimOOSD.Migrations
{
    [DbContext(typeof(DatabaseDbContext))]
    partial class DatabaseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RapPhimOOSD.Models.Login", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("password");

                    b.Property<string>("role");

                    b.Property<string>("sessionId");

                    b.Property<string>("userName");

                    b.HasKey("Id");

                    b.ToTable("Logins");

                    b.HasData(
                        new { Id = new Guid("49ec83b0-57d5-49f2-a315-6a983ca588ab"), password = "Developer", role = "New York", sessionId = "12345", userName = "John" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
